# Generated by Django 4.0.5 on 2022-06-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='message',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='service_name',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
