# Generated by Django 4.0.5 on 2022-06-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_message_service_service_name_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='team_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
