# Generated by Django 4.0.5 on 2022-06-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='port',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
