# Generated by Django 4.0.5 on 2022-06-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0005_credential_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='name',
            field=models.CharField(default='Null', max_length=100),
            preserve_default=False,
        ),
    ]
